FROM confluentinc/cp-kafka-connect:7.5.0

# Download Debezium MySQL connector manually
ADD https://repo1.maven.org/maven2/io/debezium/debezium-connector-mysql/2.6.2.Final/debezium-connector-mysql-2.6.2.Final-plugin.tar.gz /tmp/

RUN mkdir -p /usr/share/confluent-hub-components/debezium-connector-mysql \
    && tar -xzf /tmp/debezium-connector-mysql-2.6.2.Final-plugin.tar.gz -C /usr/share/confluent-hub-components/debezium-connector-mysql \
    && rm /tmp/debezium-connector-mysql-2.6.2.Final-plugin.tar.gz
