[project]
name = "bdcommon"
version = "0.1.0"
description = "Shared utils for bigdata-ml-showcase"
readme = "README.md"
requires-python = ">=3.10"
dependencies = []

[tool.setuptools.packages.find]
where = ["."]
include = ["common*"]
