# Use an official Python runtime as a parent image
FROM python:3.9.12

# Install necessary packages for locales, network tools, and other dependencies
RUN apt-get update && \
    apt-get install -y locales iputils-ping curl supervisor && \
    sed -i -e 's/# zh_TW.UTF-8 UTF-8/zh_TW.UTF-8 UTF-8/' /etc/locale.gen && \
    locale-gen zh_TW.UTF-8

# Set environment variables for locale
ENV LANG=zh_TW.UTF-8
ENV LC_ALL=zh_TW.UTF-8

# Create a new user 'appuser'
RUN useradd -m appuser

ARG PROJECT_CODE_PATH
# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY ${PROJECT_CODE_PATH}/requirements.txt /app/requirements.txt
# COPY ./requirements.txt /app/requirements.txt
COPY platform/search_system/FastAPI_service/start_services.sh /start_services.sh
# Copy project code into container (everything from context)
COPY ${PROJECT_CODE_PATH} /app

RUN chmod +x /start_services.sh

# Create the logs directory and set permissions
RUN mkdir -p /app/logs && \
    chown -R appuser:appuser /app/logs && \
    chmod -R 775 /app/logs

# Switch to the new user
USER appuser

# Update PATH environment variable
ENV PATH="/home/appuser/.local/bin:${PATH}"

# Could run --no-cache-dir for 
RUN pip install --user -r requirements.txt

# Copy supervisor config
# COPY supervisord.conf /etc/supervisord.conf
COPY platform/search_system/FastAPI_service/supervisord.conf /etc/supervisord.conf

# Expose both ports
EXPOSE 3002 8501

# Run supervisor as the main process
CMD ["supervisord", "-c", "/etc/supervisord.conf"]

