FROM confluentinc/cp-kafka-connect:7.6.0

# Install Debezium MySQL connector
RUN curl -L https://repo1.maven.org/maven2/io/debezium/debezium-connector-mysql/2.6.2.Final/debezium-connector-mysql-2.6.2.Final-plugin.tar.gz \
    -o /tmp/debezium-mysql.tar.gz \
 && mkdir -p /usr/share/confluent-hub-components/debezium-connector-mysql \
 && tar -xzf /tmp/debezium-mysql.tar.gz -C /usr/share/confluent-hub-components/debezium-connector-mysql \
 && rm /tmp/debezium-mysql.tar.gz

COPY ./kafka/confluentinc-kafka-connect-elasticsearch-14.1.0.zip /usr/share/confluent-hub-components/elasticsearch

USER root

RUN yum install -y unzip && yum clean all

COPY ./kafka/confluentinc-kafka-connect-elasticsearch-14.1.0.zip \
     /usr/share/confluent-hub-components/elasticsearch

USER appuser
