status = error
name = SparkLog4j2

filters = threshold

filter.threshold.type = ThresholdFilter
filter.threshold.level = warn

appenders = console

appender.console.type = Console
appender.console.name = STDOUT
appender.console.target = SYSTEM_OUT
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{HH:mm:ss} %-5p %c{1}: %m%n

loggers = root

logger.root.level = warn
logger.root.appenderRefs = stdout
logger.root.appenderRef.stdout.ref = STDOUT
