# kafka
FROM bitnami/kafka:3.5

USER root

# COPY ./spark_jobs/requirements.txt /tmp/requirements.txt
# RUN pip install -r /tmp/requirements.txt

COPY ./airflow/include/dependencies/* /opt/bitnami/spark/jars/
# COPY ./airflow/include/dependencies/* /opt/bitnami/kafka/libs/jars

# COPY ./dist/bdcommon-0.1.0-py3-none-any.whl /tmp/
# RUN pip install --no-cache-dir /tmp/bdcommon-0.1.0-py3-none-any.whl

ENV DEBIAN_FRONTEND=noninteractive

ENV PYSPARK_DRIVER_PYTHON_OPTS=""

RUN apt-get update && apt-get install -y wget &&\
    rm -rf /var/lib/apt/lists/*

RUN mkdir -p /opt/bitnami/spark/logs && \
    chown -R 1000:100 /opt/bitnami/spark/logs
    
# USER jovyan
