services:

  # --------------------
  # PostgreSQL
  # --------------------
  # postgres_db:
  #   image: postgres:12
  #   container_name: postgres_db
  #   environment:
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_DB: ${POSTGRES_DB}
  #     TZ: ${TZ}
  #   volumes:
  #     - ./volumes/postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "${POSTGRES_PORT}:5432"
  #   networks:
  #     - bigdata-net
  #   profiles: ["storage","search","test","dev","full"]

  postgres_init:
    image: postgres:12
    volumes:
      - ./postgres/init_postgres.sh:/init_postgres.sh
    entrypoint: ["/bin/sh", "/init_postgres.sh"]
    profiles: ["storage","search","test","dev","full"]
    networks:
      - bigdata-net


  # --------------------
  # Elasticsearch
  # --------------------
  # elasticsearch:
  #   build:
  #     context: ./search_system
  #     dockerfile: Dockerfile_es
  #   container_name: elasticsearch
  #   environment:
  #     discovery.type: single-node
  #     xpack.security.enabled: "true"
  #     ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:9200"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 10
  #   volumes:
  #     - ./search_system/es_certs/http_ca.crt:/usr/share/elasticsearch/config/certs/http_ca.crt
  #     - ./volumes/es_data:/usr/share/elasticsearch/data
  #   ports:
  #     - "${ES_PORT}:9200"
  #   profiles: ["search","test","dev","full","integration_test"]
  #   networks:
  #     - bigdata-net

  # elastic_indices_init:
  #   image: curlimages/curl:latest
  #   build: 
  #     context: ./search_system
  #     dockerfile: Dockerfile_es_init
  #   command: ["bash", "-c", "/app/init_es.py"]
  #   networks:
  #     - bigdata-net
  #   profiles: ["search","test","dev","full"]   


  # --------------------
  # MinIO
  # --------------------
  # minio:
  #   image: minio/minio
  #   container_name: minio
  #   environment:
  #     MINIO_ROOT_USER: ${MINIO_ROOT_USER}
  #     MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
  #   volumes:
  #     - ./volumes/minio-data:/data
  #     - /mnt/ssd/minio-hot:/data
  #   command: server /data --console-address ":9001"
  #   ports:
  #     - "${MINIO_API_PORT}:9000"
  #     - "${MINIO_CONSOLE_PORT}:9001"
  #   profiles: ["storage","full"]
  #   networks:
  #     - bigdata-net

  # # --------------------
  # # MinIO Bucket Init
  # # --------------------
  createbucket:
    image: minio/mc
    # depends_on:
    #   - minio
    entrypoint: >
      /bin/sh -c "
        sleep 5;
        mc alias set local ${MINIO_PROTOCOL}://${MINIO_HOST}:${MINIO_PORT} ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD};
        mc mb -p local/${ICEBERG_BUCKET};
        mc mb -p local/${MEDIA_BUCKET};
        mc policy set public local/${ICEBERG_BUCKET};
        mc policy set public local/${MEDIA_BUCKET};
        exit 0;
      "
    profiles: ["storage","full"]
    networks:
      - bigdata-net


  # --------------------
  # FastAPI Search Service
  # --------------------
  fastapi_search_service:
    build:
      context: .
      dockerfile: search_system/Dockerfile_py
    container_name: fastapi_search_service
    volumes:
      - ./search_system/es_certs:/usr/certs
      - ./search_system/FastAPI_service/code:/app/code
    environment:
      ES_USERNAME: ${ES_USERNAME}
      ES_PASSWORD: ${ELASTIC_PASSWORD}
      ES_HOST: ${ES_HOST}
      ES_CA_CERT: ${ES_CA_CERT}
    ports:
      - "${FASTAPI_PORT}:3002"
      - "${STREAMLIT_PORT}:8501"
    profiles: ["search","test","dev","full"]
    networks:
      - bigdata-net

  # --------------------
  # Kafka
  # --------------------
  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka
    environment:
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: ${KAFKA_CONTROLLER_QUORUM_VOTERS}

      KAFKA_LISTENERS: ${KAFKA_LISTENERS}
      KAFKA_ADVERTISED_LISTENERS: ${KAFKA_ADVERTISED_LISTENERS}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: ${KAFKA_LISTENER_SECURITY_PROTOCOL_MAP}

      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

      CLUSTER_ID: ${KAFKA_CLUSTER_ID}
    ports:
      - "${KAFKA_PORT}:9092"
    profiles: ["streaming","test","dev","full"]
    networks:
      - bigdata-net


  # --------------------
  # Kafka Connect
  # --------------------
  kafka-connect:
    build:
      context: .
      dockerfile: kafka/Dockerfile_connect
    container_name: kafka-connect
    environment:
      CONNECT_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      CONNECT_GROUP_ID: ${CONNECT_GROUP_ID}

      CONNECT_CONFIG_STORAGE_TOPIC: ${CONNECT_CONFIG_TOPIC}
      CONNECT_OFFSET_STORAGE_TOPIC: ${CONNECT_OFFSET_TOPIC}
      CONNECT_STATUS_STORAGE_TOPIC: ${CONNECT_STATUS_TOPIC}

      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter

      CONNECT_REST_ADVERTISED_HOST_NAME: kafka-connect
      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components
    ports:
      - "${KAFKA_CONNECT_PORT}:8083"
    depends_on:
      - kafka
    profiles: ["streaming","test","dev","full"]
    networks:
      - bigdata-net


  # --------------------
  # Spark Master
  # --------------------
  spark-master:
    build:
      context: .
      dockerfile: spark_jobs/Dockerfile
    container_name: spark-master
    command: >
      bash -c "/opt/spark/sbin/start-master.sh && tail -f /dev/null"
    environment:
      SPARK_MODE: master
      SPARK_MASTER_HOST: spark-master
      SPARK_MASTER_PORT: 7077
      SPARK_MASTER_WEBUI_PORT: 8080
      PYSPARK_NO_DRIVER: "true"
    ports:
      - "${SPARK_MASTER_PORT}:7077"
      - "${SPARK_MASTER_UI_PORT}:8080"
    profiles: ["spark","full"]
    networks:
      - bigdata-net


  # --------------------
  # Spark Worker 1
  # --------------------
  spark-worker-1:
    build:
      context: .
      dockerfile: spark_jobs/Dockerfile
    container_name: spark-worker-1
    command: >
      bash -c "/opt/spark/sbin/start-worker.sh spark://spark-master:7077 && tail -f /dev/null"
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark-master:7077
      SPARK_WORKER_MEMORY: ${SPARK_WORKER_MEMORY}
      SPARK_WORKER_CORES: ${SPARK_WORKER_CORES}
    profiles: ["spark","full"]
    networks:
      - bigdata-net

  jupyter:
    build:
      context: .
      dockerfile: spark_jobs/Dockerfile_jupyter
    container_name: jupyter
    volumes:
      # - ./airflow/include/dependencies:/home/jovyan/work/dependencies
      - ./volumes/jupyterlab:/home/jovyan/work/jupyter
    environment:
      - GRANT_SUDO=yes
      - PYSPARK_NO_DRIVER=true
      - PYSPARK_SUBMIT_ARGS=--jars /opt/bitnami/spark/jars/delta-core_2.12-3.1.0.jar,/opt/bitnami/spark/jars/delta-storage-3.1.0.jar pyspark-shell
      - JUPYTER_ENABLE_LAB=yes
    ports:
      - "8888:8888"
    profiles:
      - sparks
    command: start-notebook.sh --NotebookApp.token='' --NotebookApp.password='' --ip=0.0.0.0
    networks:
      - bigdata-net
      
  # --------------------
  # Iceberg REST Catalog
  # --------------------
  iceberg-rest:
    image: tabulario/iceberg-rest
    container_name: iceberg-rest
    ports:
      - "${ICEBERG_REST_PORT}:8181"
    environment:
      CATALOG_CATALOG__IMPL: org.apache.iceberg.jdbc.JdbcCatalog

      CATALOG_URI: jdbc:postgresql://${ICEBERG_DB_HOST}:5432/${ICEBERG_DB_NAME}
      CATALOG_JDBC_USER: ${POSTGRES_USER}
      CATALOG_JDBC_PASSWORD: ${POSTGRES_PASSWORD}

      AWS_ACCESS_KEY_ID: ${MINIO_ROOT_USER}
      AWS_SECRET_ACCESS_KEY: ${MINIO_ROOT_PASSWORD}
      AWS_REGION: ${AWS_REGION}

      CATALOG_WAREHOUSE: s3://${ICEBERG_BUCKET}/

      CATALOG_IO__IMPL: org.apache.iceberg.aws.s3.S3FileIO

      CATALOG_S3_ENDPOINT: ${MINIO_PROTOCOL}://${MINIO_HOST}:${MINIO_PORT}
      CATALOG_S3_PATH_STYLE_ACCESS: "true"
    profiles: ["spark","iceberg","full"]
    networks:
      - bigdata-net

  # --------------------
  # analysis tools
  # --------------------
  trino:
    image: trinodb/trino:latest
    container_name: trino
    ports:
      - "8085:8080"
    volumes:
      - ./trino/etc:/etc/trino
    env_file:
      - .env
    profiles:
      - iceberg
    depends_on:
      - iceberg-rest
    networks:
      - bigdata-net

networks:
  bigdata-net:
    driver: bridge
    ipam:
      config:
        - subnet: ${DOCKER_SUBNET}
          gateway: ${DOCKER_GATEWAY}