networks:
  bigdata-net:
    external: true
    ipam:
      config:
        - subnet: 172.30.0.0/16
          gateway: 172.30.0.1

services:
  # Attach only the services you want to a custom network.
  # DO NOT redefine them unless you're modifying image/build etc.

  scheduler:
    # volumes:
    #   - ../spark_jobs/dependencies:/usr/local/airflow/jars   # mount JDBC jars here
    networks:
      - bigdata-net

  dag-processor:
    networks:
      - bigdata-net

  triggerer:
    networks:
      - bigdata-net

  postgres:
    networks:
      - bigdata-net

  api-server:
    networks:
      - bigdata-net
    # ports:
    #   - 0.0.0.0:8080:8080

