FROM mysql:5.7

# Copy schema into the init directory
# COPY sql/init.sql /docker-entrypoint-initdb.d/


ENV MYSQL_ROOT_PASSWORD=!QAZ2wsx
ENV MYSQL_DATABASE=whole_corp
ENV MYSQL_CHARSET = utf8mb4
ENV MYSQL_COLLATION = utf8mb4_general_ci
